### PR TITLE
styling for the interim design

### PR DESCRIPTION
**Pull request by iamwebrocker**
a little bit of styling, based on one base color ($ci-color) in style.scss. change to your liking.

### CODE REVIEW

**Comment by mxstbr** [comment]
+1 for the typography, like the sans for body copy. I don't dig the color you chose, but I love your scale.

I think the header background gradient is a bit too... bold? Not quite sure if I can do that on my own, but could make a new pull request w/o the header background gradient? I'd rather go w/o it for now.

**Comment by mxstbr** [comment]
Nevermind, I just changed it myself. Have a look now and tell me what you think!

EDIT: Not happy with the base color as-is, but we can obviously quickly iterate through different ones, so that shouldn't be a concern right now. (Thank god for SASS, wow)

**Comment by iamwebrocker** [comment]
oh, I just changed the color theme in that moment…I think a subtle gradient is nice, tho...

**Comment by mxstbr** [comment]
That's true, but I think it'd looks nicer if it faded in with the background-color, wouldn't it?

**Comment by mxstbr** [comment]
I think you misunderstood me, I don't mind the gradient per-se, but the whole header-color-thingy. I think it's just too bold to look good, but of course you need a gradient there if you want to keep it. I'd just remove the header-color-thingy and merge that into the gh-pages branch, because I love the rest of the typography.

**Comment by iamwebrocker** [comment]
well, I opted for a clean distinction between the not-so-important header/branding area and the content area. for visual balance I'd put the 'logo' in light on the darker background. so the eye would be drawn there and directly then down to the bright content-area, where the beef is. the darker header background will set this area back a bit, esp if it is full-width - so that the "page", the content area, sits in the foreground. well, this is the interim stage anyway :-), so go ahead as you see fit -- nothing is set in stone, right?

**Comment by mxstbr** [comment]
I agree that we have to seperate the header area from the body area, but right now it's too bold for me. I changed the gradient to `linear-gradient(to bottom,lighten($ci-color,60),$lightgrey)`, which I think is preferable. Have a look and tell me what you think!

**Comment by iamwebrocker** [comment]
Yes sure, ship it! :)) I tried to keep it one-color based for simplicity and easy changeability, not b/c I'm too attached to that theme.
[Edit] - Just tweaked the footer to reflect the header's gradient, gives a nice fadein/out effect to the main content area. Not very fond of the baby blue, but that's down to matter of taste now, so no biggie.

**Comment by mxstbr** [comment]
Not a fan of the blue either, I'll try other ones, give me a second.

**Comment by mxstbr** [comment]
What about a darker blue, e.g. `#0B486B` or my favorite so far `#394856`? Or would you rather have a different color altogether?

**Comment by mstoiber** [comment]
Or even darker, which I like more: #394856

**Comment by mxstbr** [comment]
Hey @anselmh, could you sign the design off as well? I think the three main contributors should agree on the design before we put it live.

**Comment by anselmh** [comment]
I don’t like the gradient. It looks like an old 90y design of a website. Just leave it out and I’m fine. :)

**Comment by mxstbr** [comment]
:+1: Anselm. Are you alright with that @iamwebrocker, and with `#394856`? (Pull commit df745cb to see the design)

**Comment by iamwebrocker** [comment]
yes sure, go! 90ies, pfff. ;-))

**Comment by iamwebrocker** [comment]
design by comittee… *sigh :-)

**Comment by iamwebrocker** [comment]
hm. I think what Anselm meant was leave out the gradient, but keep the header/footer color as solids?
The all-white version it is now (df745cb) isn't much of an improvement to the current live version. but guys, srsly, if the discussion even for the _interim_ version is this long, what happens for the _real_ one? We just discussed/iterated the thing full circle instead of ship a quick 1st version.

**Comment by mxstbr** [comment]
Well, I just pushed that one (df745cb) live before I saw your comment. 

But yeah, you're right, we didn't change much, even though the typography changed quite nicely. Let's just do the real design asap and simply leave the interim design be for now?

**Pull request closed without merging**
